AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  passroute-crawler

Globals:
  Function:
    Timeout: 300
    LoggingConfig:
      LogFormat: JSON

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 18 * * ? *)
            Enabled: false 
